name: Lint Check

on:
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - '**.md'

jobs:
  lint-check:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          submodules: true

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle

      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Check lint
        run: ./gradlew ktlintFormat

      - name: Upload report
        # If lint fails we give report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: app/build/reports/ktlint/*/*.xml

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Actions Fix linting
